// Persistent, self-flushing attendance event queue (web/foreground layer).
//
// Persists across app restarts (localStorage), retries automatically, flushes on
// network recovery, preserves each event's original timestamp + id, and relies
// on the stable event id + server idempotency so retries never double-record.
//
// (Native background transitions are queued natively when offline; this handles
// events generated by the web/foreground layer — reconciliation + forwarded
// native transitions while the app is alive.)

import {
  dequeue,
  enqueue,
  makeEventId,
  markAttempt,
  pruneExhausted,
  selectDueForRetry,
  type QueuedAttendanceEvent,
} from "./offlineQueue.ts";

const STORAGE_KEY = "attendance.offlineQueue.v1";

function load(): QueuedAttendanceEvent[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function save(queue: QueuedAttendanceEvent[]): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(queue));
  } catch {
    /* storage full / unavailable — best effort */
  }
}

export type NewAttendanceEvent = {
  jobId: string | number;
  zone: "arrival" | "wake";
  transition: "enter" | "exit";
  occurredAt: string;
  latitude?: number | null;
  longitude?: number | null;
  accuracyMeters?: number | null;
};

/** Add an event to the durable queue (idempotent on the stable event id). */
export function enqueueAttendanceEvent(event: NewAttendanceEvent): void {
  const eventId = makeEventId(event);
  save(enqueue(load(), { ...event, jobId: String(event.jobId), eventId }));
}

let flushing = false;

/**
 * Try to submit every due event. Successful sends (and server-side duplicates)
 * are removed; failures increment the attempt counter and stay queued. Safe to
 * call repeatedly; a single flush runs at a time.
 */
export async function flushAttendanceQueue(): Promise<void> {
  if (flushing) return;
  if (typeof navigator !== "undefined" && navigator.onLine === false) return;
  flushing = true;
  try {
    let queue = pruneExhausted(load());
    save(queue);
    for (const event of selectDueForRetry(queue)) {
      let ok = false;
      try {
        const res = await fetch("/api/jobsite-time/events", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            jobId: event.jobId,
            zone: event.zone,
            transition: event.transition,
            occurredAt: event.occurredAt, // preserved original timestamp
            latitude: event.latitude,
            longitude: event.longitude,
            accuracyMeters: event.accuracyMeters,
            source: "jobsite_auto",
          }),
        });
        // 2xx OR a definitive rejection both clear the item (a duplicate is a
        // success; a 4xx that isn't 429 won't succeed on retry either).
        ok = res.ok || (res.status >= 400 && res.status < 500 && res.status !== 429);
      } catch {
        ok = false; // network error — keep for retry
      }
      queue = ok ? dequeue(queue, event.eventId) : markAttempt(queue, event.eventId);
      save(queue);
    }
  } finally {
    flushing = false;
  }
}

let autoFlushStarted = false;

/** Flush now, on network recovery, and on a periodic timer. Idempotent. */
export function startAttendanceQueueAutoFlush(): () => void {
  if (typeof window === "undefined") return () => {};
  void flushAttendanceQueue();
  if (autoFlushStarted) return () => {};
  autoFlushStarted = true;

  const onOnline = () => void flushAttendanceQueue();
  window.addEventListener("online", onOnline);
  const timer = window.setInterval(() => void flushAttendanceQueue(), 60_000);

  return () => {
    window.removeEventListener("online", onOnline);
    window.clearInterval(timer);
    autoFlushStarted = false;
  };
}

export function getQueuedAttendanceEventCount(): number {
  return load().length;
}
