// Self-flushing attendance event queue (web/foreground layer).
//
// Persists across app termination and device restart, retries with exponential
// backoff on connectivity recovery / app launch / resume / a controlled
// interval, refreshes an expired credential rather than burning retries on it,
// quarantines permanently-rejected events instead of retrying them forever, and
// preserves each event's ORIGINAL timestamp and submission order.
//
// Native background transitions are POSTed directly by the native layer and
// queued natively when offline (see the plugin sources). This handles events
// generated by the web/foreground layer — reconciliation and native transitions
// forwarded while the app is alive — and shares the durable store with the
// native queue so diagnostics report one depth, not two.

import {
  classifyFailure,
  dequeue,
  enqueue,
  isDelivered,
  makeEventId,
  markFailure,
  pruneQuarantined,
  queueDiagnostics,
  selectDueForRetry,
  type FailureClass,
  type QueueDiagnostics,
  type QueuedAttendanceEvent,
} from "./offlineQueue.ts";
import {
  EMPTY_META,
  loadQueue,
  peekQueueSync,
  saveQueue,
  type QueueMeta,
} from "./offlineQueueStorage.ts";
import { enrollDeviceCredential, getStableDeviceId } from "./deviceCredentialClient.ts";

export type NewAttendanceEvent = {
  jobId: string | number;
  assignmentId?: string | null;
  zone: "arrival" | "wake";
  transition: "enter" | "exit";
  occurredAt: string;
  latitude?: number | null;
  longitude?: number | null;
  accuracyMeters?: number | null;
  source?: "jobsite_auto" | "manual";
};

/** Add an event to the durable queue (idempotent on the stable event id). */
export async function enqueueAttendanceEvent(event: NewAttendanceEvent): Promise<void> {
  const { queue, meta } = await loadQueue();
  const eventId = makeEventId(event);
  const next = enqueue(queue, {
    ...event,
    jobId: String(event.jobId),
    deviceId: getStableDeviceId(),
    eventId,
  });
  await saveQueue(next, meta);
}

let flushing = false;
// One credential refresh per flush. A rotation that does not fix the 401 must
// not spin.
let refreshedThisFlush = false;

async function submit(event: QueuedAttendanceEvent): Promise<{ status: number | null; reason: string }> {
  try {
    const res = await fetch("/api/jobsite-time/events", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        jobId: event.jobId,
        zone: event.zone,
        transition: event.transition,
        // The ORIGINAL timestamp — never "now". An arrival that happened while
        // offline at 6:50 is still a 6:50 arrival when it syncs at 9:00.
        occurredAt: event.occurredAt,
        latitude: event.latitude,
        longitude: event.longitude,
        accuracyMeters: event.accuracyMeters,
        source: event.source,
      }),
    });
    return { status: res.status, reason: `HTTP ${res.status}` };
  } catch (error) {
    return { status: null, reason: error instanceof Error ? error.message : "network error" };
  }
}

/**
 * Submit every due event. Safe to call repeatedly and concurrently; a single
 * flush runs at a time.
 *
 * Each pass sends at most the oldest pending event per job, so an exit can
 * never overtake the enter that opened its shift. Remaining events go out on
 * the next pass, which is scheduled immediately when there is more to send.
 */
export async function flushAttendanceQueue(): Promise<QueueDiagnostics> {
  if (flushing) return getAttendanceQueueDiagnostics();
  if (typeof navigator !== "undefined" && navigator.onLine === false) {
    return getAttendanceQueueDiagnostics();
  }
  flushing = true;
  refreshedThisFlush = false;
  try {
    const loaded = await loadQueue();
    let queue = pruneQuarantined(loaded.queue);
    let meta: QueueMeta = { ...loaded.meta };
    let due = selectDueForRetry(queue);

    // Keep going while a job's queue still has ready work — the per-job head
    // rule means one pass would otherwise send only one event per job.
    let guard = 0;
    while (due.length > 0 && guard < 200) {
      guard += 1;
      for (const event of due) {
        const { status, reason } = await submit(event);

        if (status !== null && isDelivered(status)) {
          queue = dequeue(queue, event.eventId);
          meta = { ...meta, lastSuccessfulSyncAt: new Date().toISOString() };
          continue;
        }

        const failure: FailureClass = classifyFailure(status);
        // An expired or rotated credential is not the event's fault. Re-enroll
        // once, then let the event retry on the next pass with a fresh token.
        if (failure === "auth" && !refreshedThisFlush) {
          refreshedThisFlush = true;
          await enrollDeviceCredential().catch(() => false);
        }
        queue = markFailure(queue, event.eventId, failure, reason);
        meta = { ...meta, lastFailureAt: new Date().toISOString(), lastFailureReason: reason };
      }
      await saveQueue(queue, meta);
      const next = selectDueForRetry(queue);
      // Stop when the next pass would retry the same events (i.e. nothing was
      // delivered) rather than looping on a failing queue.
      if (next.length === due.length && next.every((e, i) => e.eventId === due[i]?.eventId)) break;
      due = next;
    }

    await saveQueue(queue, meta);
    return queueDiagnostics(queue, meta);
  } finally {
    flushing = false;
  }
}

let autoFlushStarted = false;

/**
 * Flush now and on every opportunity the platform gives us: network recovery,
 * app launch, returning to the foreground, and a controlled interval. Idempotent.
 *
 * The interval is the backstop, not the mechanism — background delivery for a
 * closed app is the native queue's job.
 */
export function startAttendanceQueueAutoFlush(): () => void {
  if (typeof window === "undefined") return () => {};
  void flushAttendanceQueue();
  if (autoFlushStarted) return () => {};
  autoFlushStarted = true;

  const flush = () => void flushAttendanceQueue();
  const onVisible = () => {
    if (document.visibilityState === "visible") flush();
  };

  window.addEventListener("online", flush);
  document.addEventListener("visibilitychange", onVisible);
  // Capacitor emits this when the app returns from the background; harmless on
  // the web, where it simply never fires.
  window.addEventListener("resume", flush);
  const timer = window.setInterval(flush, 60_000);

  return () => {
    window.removeEventListener("online", flush);
    document.removeEventListener("visibilitychange", onVisible);
    window.removeEventListener("resume", flush);
    window.clearInterval(timer);
    autoFlushStarted = false;
  };
}

/** Queue depth, oldest event, last sync, and last failure — for diagnostics. */
export function getAttendanceQueueDiagnostics(): QueueDiagnostics {
  const { queue, meta } = peekQueueSync();
  return queueDiagnostics(queue, meta);
}

export function getQueuedAttendanceEventCount(): number {
  return getAttendanceQueueDiagnostics().pendingCount;
}

/** Async diagnostics that read the durable (native) store rather than the mirror. */
export async function readAttendanceQueueDiagnostics(): Promise<QueueDiagnostics> {
  const { queue, meta } = await loadQueue().catch(() => ({ queue: [], meta: { ...EMPTY_META } }));
  return queueDiagnostics(queue, meta);
}
